**basics of numpy**

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,9,12])

In [3]:
myarr[0]

3

In [4]:
myarr1=np.array([[3,6,32,7]],np.int64)

In [5]:
myarr1[0,2]

32

In [6]:
myarr.shape

(4,)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr1.dtype

dtype('int64')

In [9]:
myarr1[0,3]=49

In [10]:
myarr1

array([[ 3,  6, 32, 49]], dtype=int64)

**array creation in numpy**

**i.conversion from other python structures (eg.,lists,tuples)**

In [11]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
np.array({12,16,20})

array({16, 12, 20}, dtype=object)

**ii.intrinsic numpy array creation objects (eg.,arange,ones,zeroes,etc.)**

In [17]:
zeros=np.zeros((2, 5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
rng=np.arange(100)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
lspace=np.linspace(1,5,12)

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 1.89146896e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.33510679e-306],
       [2.22522597e-306, 1.33511018e-306, 6.23057689e-307,
        1.33511290e-306, 1.78019082e-306, 8.45559303e-307],
       [8.06612616e-308, 6.89810244e-307, 1.22387550e-307,
        2.22522596e-306, 8.34423917e-308, 9.79107193e-307]])

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [29]:
ide=np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.shape

(45, 45)

In [32]:
ide.size

2025

In [33]:
arr=np.arange(105)

In [34]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104])

In [35]:
arr=arr.reshape(7,15)

In [36]:
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14],
       [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104]])

In [37]:
arr=arr.ravel()

In [38]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104])

In [39]:
arr.shape

(105,)

In [40]:
arr.size

105

**Numpy Axis**

In [41]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [42]:
ar=np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.sum(axis=0)

array([12,  8,  9])

In [45]:
ar.sum(axis=1)

array([ 6, 15,  8])

**Numpy Attributes and Methods**

In [46]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
ar.flat

In [48]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim

2

In [50]:
ar.size

9

In [51]:
ar.shape

(3, 3)

In [52]:
ar.nbytes

36

In [53]:
one=np.array([1,2,3,45,5])

In [54]:
one.argmax()

3

In [55]:
one.argmin()

0

In [56]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [57]:
ar.argmin()

8

In [58]:
ar.argmax()

6

In [59]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [60]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [61]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [62]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [64]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [65]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [66]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
ar.sum()

29

In [69]:
ar.min()

0

In [70]:
ar.max()

7

In [71]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [73]:
type(np.where(ar>5))

tuple

In [74]:
np.count_nonzero(ar)

8

In [75]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [76]:
type(np.nonzero(ar))

tuple

In [77]:
import sys

In [78]:
py_ar=[0,4,55,2]

In [79]:
np_ar=np.array(py_ar)

In [80]:
sys.getsizeof(1)*len(py_ar)

112

In [81]:
np_ar.itemsize*np_ar.size

16

In [82]:
np_ar.tolist()

[0, 4, 55, 2]